[Учебник по языку программирования Python](http://dfedorov.spb.ru/python3/book.pdf)

__NumPy__ - open-source модуль для python, который предоставляет общие математические и числовые операции в виде пре-скомпилированных, быстрых функций.

[Официальное описание NumPy](https://numpy.org/)

[An introduction to Numpy and Scipy](https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf)

[Learn NUMPY in 5 minutes - BEST Python Library!](https://www.youtube.com/watch?v=xECXZ3tyONo)

<font size="72"><h1><center>NumPy</center></h1></font>
<h1><center>Вводный курс</center></h1>

## Импорт модуля NumPy

In [1]:
import numpy as np

## Массивы

In [2]:
a1 = np.array([1,2,3,4],float)
a1

array([1., 2., 3., 4.])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a1[:2]

array([1., 2.])

In [5]:
a1[3]

4.0

In [6]:
a1[0] = 5.
a1

array([5., 2., 3., 4.])

In [7]:
a2 = np.array([[1, 2, 3], [4, 5, 6]], float)
a2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
a2[0,0]

1.0

In [9]:
a2[0,1]

2.0

In [10]:
a2[1,:]

array([4., 5., 6.])

In [11]:
a2[:,2]

array([3., 6.])

In [12]:
a2[-1:, -2:]

array([[5., 6.]])

In [13]:
a2.shape

(2, 3)

In [14]:
a2.dtype

dtype('float64')

In [15]:
len(a2)

2

In [16]:
2 in a2

True

In [17]:
0 in a2

False

In [18]:
a3 = np.array(range(10), float)
a3

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
a4 = a3.reshape((5, 2))
a4

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [20]:
a4.shape

(5, 2)

In [21]:
a5 = np.array([1, 2, 3], float)
b5 = a5
c5 = a5.copy();

In [22]:
a5[0]=0
a5

array([0., 2., 3.])

In [23]:
b5

array([0., 2., 3.])

In [24]:
c5

array([1., 2., 3.])

In [25]:
a6 = np.array([1, 2, 3], float)
a6.tolist()

[1.0, 2.0, 3.0]

In [26]:
list(a6)

[1.0, 2.0, 3.0]

In [27]:
a7 = np.array([1, 2, 3], float)
s7 = a7.tostring()
s7

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [28]:
np.fromstring(s7)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([1., 2., 3.])

In [29]:
a8 = np.array([1, 2, 3], float)
a8

array([1., 2., 3.])

In [30]:
a8.fill(8765758748478)
a8

array([8.76575875e+12, 8.76575875e+12, 8.76575875e+12])

In [31]:
a9 = np.array([[1, 2, 3], [4, 5, 6]], float)
a9

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
a9.flatten()

array([1., 2., 3., 4., 5., 6.])

In [33]:
a10 = np.array([1,2], float)
b10 = np.array([3,4,5,6], float)
c10 = np.array([7,8,9], float)
np.concatenate((a10, b10, c10))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
a11 = np.array([[1, 2], [3, 4]], float)
b11 = np.array([[5, 6], [7,8]], float);

In [35]:
np.concatenate((a11, b11), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [36]:
np.concatenate((a11, b11), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [37]:
a12 = np.array([1, 2, 3], float)
a12

array([1., 2., 3.])

In [38]:
a12[:,np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [39]:
a12[np.newaxis,:]

array([[1., 2., 3.]])

## Другие пути создания массивов

In [40]:
np.arange(5, dtype=float)

array([0., 1., 2., 3., 4.])

In [41]:
np.arange(1, 6, 2, dtype=int)

array([1, 3, 5])

In [42]:
np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [44]:
a13 = np.array([[1,2,3],[1,2,3]],float)

In [45]:
np.zeros_like(a13)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.ones_like(a13)*228

array([[228., 228., 228.],
       [228., 228., 228.]])

In [47]:
np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.eye(4, k=1, dtype=float)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

## Математические операции над массивами

In [49]:
a14 = np.array([1,2,3], float)
b14 = np.array([5,2,6], float)

In [50]:
a14+b14

array([6., 4., 9.])

In [51]:
a14-b14

array([-4.,  0., -3.])

In [52]:
a14*b14

array([ 5.,  4., 18.])

In [53]:
b14/a14

array([5., 1., 2.])

In [54]:
a14%b14

array([1., 0., 3.])

In [55]:
b14**a14

array([  5.,   4., 216.])

In [56]:
a15 = np.array([[1,2], [3,4]], float)
b15 = np.array([[2,0], [1,3]], float)
a15*b15

array([[ 2.,  0.],
       [ 3., 12.]])

In [57]:
a16 = np.array([1,2,3], float)
b16 = np.array([4,5], float)
a16 + b16

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [58]:
a17 = np.array([[1, 2], [3, 4], [5, 6]], float)
b17 = np.array([-1, 3], float)
a17+b17

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [59]:
a18 = np.array([1, 4, 9], float)
np.sqrt(a18)

array([1., 2., 3.])

In [60]:
a19 = np.array([1.1, 1.5, 1.9], float)
np.floor(a19)

array([1., 1., 1.])

In [61]:
np.ceil(a19)

array([2., 2., 2.])

In [62]:
np.rint(a19)

array([1., 2., 2.])

In [63]:
np.pi

3.141592653589793

In [64]:
np.e

2.718281828459045

## Перебор элементов массива

In [65]:
a20 = np.array([1, 4, 5], int)
for x in a20:
    print(x)

1
4
5


In [66]:
a21 = np.array([[1, 2], [3, 4], [5, 6]], float)
for (x, y) in a21:
       print(x * y)

2.0
12.0
30.0


## Базовые операции над массивами

In [67]:
a22= np.array([2, 4, 3], float)
a22.sum()

9.0

In [68]:
a22.prod()

24.0

In [69]:
a22.max()

4.0

In [70]:
a22.min()

2.0

In [71]:
a22.argmax()

1

In [72]:
a22.argmin()

0

In [73]:
a22.sort()
a22

array([2., 3., 4.])

In [74]:
a23 = np.array([6, 2, 5, -1, 0], float)
a23.clip(0, 5)

array([5., 2., 5., 0., 0.])

In [75]:
a24 = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a24)

array([1., 4., 5., 7.])

In [76]:
a25 = np.array([[1, 2], [3, 4]], float)
a25.diagonal()

array([1., 4.])

## Операторы сравнения и тестирование значений

In [77]:
a26 = np.array([1, 3, 0], float)
b26 = np.array([0, 3, 2], float)
a26 > b26

array([ True, False, False])

In [78]:
a26 == b26

array([False,  True, False])

In [79]:
a26 <= b26

array([False,  True,  True])

In [80]:
c26 = a26 > b26
c26

array([ True, False, False])

In [81]:
a26 > 2

array([False,  True, False])

In [82]:
any(c26)

True

In [83]:
all(c26)

False

In [84]:
np.logical_and(a26 > 0, a26 < 3)

array([ True, False, False])

In [85]:
np.logical_not(c26)

array([False,  True,  True])

In [86]:
np.logical_or(a26 > 2, c26)

array([ True,  True, False])

In [87]:
np.where(a26 != 1, a26*4, a26)

array([ 1., 12.,  0.])

In [88]:
np.where(a26>0,3,2)

array([3, 3, 2])

In [89]:
a26[a26>0]

array([1., 3.])

In [90]:
a27 = np.array([2, 4, 6, 8], float)
b27 = np.array([0, 0, 1, 3, 2, 1], int)
a27[b27]

array([2., 2., 4., 8., 6., 4.])

In [91]:
a28 = np.array([[1, 4], [9, 16]], float)
b28 = np.array([0, 0, 1, 1, 1], int)
c28 = np.array([0, 1, 1, 1, 0], int)
np.sqrt(a28[b28,c28])

array([1., 2., 4., 4., 3.])

In [92]:
a29 = np.array([0, 1, 2, 3, 4, 5], float)
b29 = np.array([9, 8, 7], float)
a29.put([0, 3], b29)
a29

array([9., 1., 2., 8., 4., 5.])

In [93]:
a29.put([0, 3],5)
a29

array([5., 1., 2., 5., 4., 5.])

## Векторная и матричная математика

In [94]:
a30 = np.array([1, 2, 3], float)
b30 = np.array([0, 1, 1], float)
np.dot(a30, b30)

5.0

In [95]:
a31 = np.array([[0, 1], [2, 3]], float)
b31 = np.array([2, 3], float)
np.dot(b31, a31)

array([ 6., 11.])

In [96]:
a32 = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], int)
np.linalg.det(a32)

-48.00000000000003

In [97]:
vals, vecs = np.linalg.eig(a32)
vals

array([ 8.85591316,  1.9391628 , -2.79507597])

In [98]:
vecs

array([[-0.3663565 , -0.54736745,  0.25928158],
       [-0.88949768,  0.5640176 , -0.88091903],
       [-0.27308752,  0.61828231,  0.39592263]])

In [99]:
b32 = np.linalg.inv(a32)
b32

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [100]:
np.dot(a32,b32)

array([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00, -2.77555756e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [101]:
a33 = np.array([[1, 3, 4], [5, 2, 3]], float)
U, s, Vh = np.linalg.svd(a33)
U

array([[-0.6113829 , -0.79133492],
       [-0.79133492,  0.6113829 ]])

In [102]:
s

array([7.46791327, 2.86884495])

In [103]:
Vh

array([[-0.61169129, -0.45753324, -0.64536587],
       [ 0.78971838, -0.40129005, -0.46401635],
       [-0.046676  , -0.79349205,  0.60678804]])

##  Математика полиномов

In [104]:
np.poly([-1, 1, 1, 10])

array([  1., -11.,   9.,  11., -10.])

In [105]:
np.roots([1, 4, -2, 3])

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

In [106]:
np.polyint([1, 1, 1, 1])

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

In [107]:
np.polyder([1./4., 1./3., 1./2., 1., 0.])

array([1., 1., 1., 1.])

In [108]:
np.polyval([1, -2, 0, 2], 4)

34

In [109]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0, 2, 1, 3, 7, 10, 11, 19]
np.polyfit(x, y, 2)

array([ 0.375     , -0.88690476,  1.05357143])

## Статистика

In [110]:
st1 = np.array([1, 4, 3, 8, 9, 2, 3], float)
>>> np.median(st1)

3.0

In [111]:
st2 = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
np.corrcoef(st2)

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [112]:
np.cov(st2)

array([[0.91666667, 2.08333333],
       [2.08333333, 8.91666667]])

## Случайные числа

In [113]:
np.random.seed(293423)

In [114]:
np.random.rand(5)

array([0.33677247, 0.52693437, 0.79529578, 0.78867702, 0.02147624])

In [115]:
np.random.rand(2,3)

array([[0.84612516, 0.0704939 , 0.1526965 ],
       [0.77831701, 0.80821151, 0.82198398]])

In [116]:
np.random.rand(6).reshape((2,3))

array([[0.90239653, 0.8385685 , 0.02638565],
       [0.33681448, 0.46480928, 0.61686496]])

In [122]:
np.random.random()

0.47439137492840955

In [123]:
np.random.randint(5, 10, 3)

array([9, 6, 8])

In [119]:
np.array([np.random.poisson(6.0), np.random.pareto(4), np.random.laplace(3), np.random.normal(1.5, 4.0)], float)

array([ 4.        ,  0.5923462 ,  1.4492223 , -1.52240809])

#### Задачи:

### 1.Перемножить матрицы 5x3 и 3x2 (★)

In [120]:
np.dot(np.random.rand(5,3),np.random.rand(3,2))

array([[0.78151776, 0.3512717 ],
       [0.99833399, 0.45881237],
       [0.91715567, 0.36754626],
       [0.46785993, 0.24083649],
       [0.33587991, 0.24723994]])

### 2. Дан массив, поменять знак у элементов, значения которых между 3 и 8 (★)

In [149]:
x=np.random.randint(0, 10, 10)
x

array([2, 0, 9, 5, 7, 5, 8, 8, 1, 1])

In [152]:
np.where(3<=x, -x, x)
np.where(x<=8, -x, x)

array([-2,  0,  9, -5, -7, -5, -8, -8, -1, -1])

### 3. Создать случайный вектор размера 30 и найти среднее значение всех элементов (★★)

In [154]:
x=np.random.randint(0, 100, 30)
x

array([29, 99, 66, 50, 39, 59, 23, 94, 30,  5, 77, 23, 42, 19, 56, 74, 48,
       63, 82, 12, 34, 58, 64, 26, 97, 69, 72, 28, 50, 83])

In [155]:
np.mean(x)

52.36666666666667

### 4. Создать 8x8 матрицу и заполнить её в шахматном порядке (★★)

In [161]:
m=np.zeros((8,8),dtype=int)
for i in range(-6,7,2):
    m+=np.eye(8, k=i, dtype=int)  
m

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### 5. Найти ранг матрицы (★★★)

In [197]:
np.linalg.matrix_rank(np.random.randint(0, 2, (3,3)))

2

### 6. Создать реализацию "Игры "Жизнь"" используя массивы NumPy (★★★)

# Спасибо за внимание!